apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  default.conf: |-
    upstream webapplication {
      server 127.0.0.1:5000;
    }    
    server {
      listen 80;                

      client_body_buffer_size 100M;
      client_max_body_size 100M;  
      proxy_buffers 16 16k;  
      proxy_buffer_size 16k;      

      location / {
        proxy_pass http://webapplication;
    
        proxy_set_header  Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
      location /health {
        return 200 "ok";
        add_header Content-Type text/plain;
      }
    }

